force-app/main/default/objects/Master__c/Master__c.object-meta.xml
<CustomObject>
    <description>Generic master side of a master / detail relationship.</description>
    <label>Master</label>
    <nameField>
        <label>Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <description>Count of the number of detail records</description>
    <label>Count</label>
    <summaryForeignKey>Detail__c.Master__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Sum__c.field-meta.xml
<CustomField>
    <fullName>Sum__c</fullName>
    <description>Sum of the value of all detail Records</description>
    <label>Sum</label>
    <summarizedField>Detail__c.Value__c</summarizedField>
    <summaryForeignKey>Detail__c.Master__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/Requirements.cls
@IsTest public with sharing class Requirements {
    
    @TestSetup static void setup() {
        Factory.setup();
    }

    @IsTest static void verifyMasterRollups() {

        Master__c m = [
            select Id, Count__c, Sum__c
            from Master__c
        ];

        System.assertEquals(m.Count__c, 10);
        System.assertEquals(m.Sum__c, 45);

    }

    @IsTest static void builder() {

        Account a = (new AccountBuilder())
            .withName('xyz')
            .withDescription('new description')
            .build()
            .query();

        System.assertEquals('xyz', a.Name);
        System.assertEquals('new description', a.Description);


        Contact c = (new ContactBuilder())
            .withFirstName('John')
            .withLastName('Doe')
            .withAccountId(new AccountBuilder()
                .withName('Big Corp')
                .withDescription('Big Corp Description')
                .build().id)
            .build()
            .query();

        Account bigCorp = [select Name, Description from Account where Id = :c.AccountId];

        System.assertEquals('Big Corp', bigCorp.Name);
        System.assertEquals('Big Corp Description', bigCorp.Description);
}
    }