force-app/main/default/objects/Detail__c/Detail__c.object-meta.xml
<CustomObject>
    <description>Detail side of master / detail relationship</description>
    <label>Detail</label>
    <nameField>
        <label>Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Detail__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master__c/Master__c.object-meta.xml
<CustomObject>
    <description>Generic master side of a master / detail relationship.</description>
    <label>Master</label>
    <nameField>
        <label>Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Factory.cls
public with sharing class Factory {
    
    public static Id createMaster(String name) {

        Master__c m = new Master__c(
            Name = name
        );
        insert m;

        return m.Id;
    }

    public static Id createDetail(Id masterId, Integer value) {

        Detail__c d = new Detail__c(
            Master__c = masterId,
            Value__c = value
        );
        insert d;

        return d.Id;
    }

    public static Id createAccount(String name) {
  
        Account a = new Account(
            Name = name
        );
        insert a;

        return a.Id;
    }

    public static Id createContact(String firstName, String lastName) {
        Contact c = new Contact(
            FirstName = firstName,
            LastName = lastName
        );
        insert c;

        return c.Id;
    }

    public static void setup() {

        Id masterId = createMaster('m');

        for (Integer i = 0; i < 10; i++) {
            createDetail(masterId, i);
        }

        /* create three Accounts and an unlinked Contact
        */
        createAccount('apple');
        createAccount('pear');
        createAccount('orange');

        createContact('John', 'Doe');

    }

    public static void cleanup() {
        delete [select Id from Detail__c];
        delete [select Id from Master__c];
        delete [select Id from Contact];
        delete [select Id from Account];
    }

}